name: dooadex_error_handler
description: A useful error handler
version: 0.0.7
repository: "https://github.com/Doohyeon-Kim/dooadex-error-handler.git"

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dooadex_logger: ^0.0.7
  dooadex_constants: ^0.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
